version: 2.1
jobs:
 validate:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform plan
      command:
        terraform init
 provision:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform pla
      command: |
        terraform plan -out tfapply -var-file terraform.tfvars
        terraform apply -auto-approve tfapply
workflows:
 deployment: 
  jobs:
   - validate
   - provision