version: 2.1
jobs:
 validate:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform plan
      command:
        terraform init
 provision:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform 
      command: |
        terraform init
        terraform plan -var-file terraform.tfvars
        terraform apply -var-file terraform.tfvars -auto-approve
workflows:
 deployment: 
  jobs:
   - validate
   - provision