version: 2.1
jobs:
 build:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform plan
      command: |
        terraform init -input=false
        terraform plan -out tfapply -var-file terraform.tfvars
        terraform apply -var-file=tfapply --auto-approve
workflows:
  jobs:
   - validate:
      filers:
       branches:
        ignore:
         -master