version: 2.1
jobs:
 build:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform plan
      command: |
        terraform init -input=false
workflows:
 deployment: 
  jobs:
   - build