version: 2.1
jobs:
 validate:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform plan
      command:
        terraform fmt
        terraform validate
 provision:
  docker:
   - image: hashicorp/terraform:latest
  steps:
   - checkout
   - run:
      name: checkout the code and run terraform plan
      command:
        terraform init -input=false
        terraform plan -var-file terraform.tfvars
        terraform apply -var-file terraform.tfvars --auto-approve 
workflows:
 deployment: 
  jobs:
   - validate
   - provision